"""
The `app` schema in megh_db — everything this service owns (as opposed to the
read-only `curated`/`semantic` warehouse it queries): tenants, users, login
events, conversations + turns, and the query audit trail.

`ensure_schema()` runs at startup (idempotent CREATE TABLE IF NOT EXISTS) and
seeds the default tenant + imports app/users.yaml once if app.users is empty.
All access goes through backend.db's pooled `postgres` connection.
"""
import json
import logging
from pathlib import Path

import yaml

from app import db, security
from app.config import settings

logger = logging.getLogger(__name__)

_ROOT = Path(__file__).resolve().parents[1]   # repo root

_DDL = """
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.tenants (
    tenant_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.users (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES app.tenants(tenant_id),
    username        TEXT UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    name            TEXT,
    role            TEXT NOT NULL,
    districts       TEXT[] NOT NULL DEFAULT '{}',
    blocks          TEXT[] NOT NULL DEFAULT '{}',
    schemes         TEXT[] NOT NULL DEFAULT '{}',
    granularity_cap TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_by      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_users_tenant ON app.users(tenant_id);

CREATE TABLE IF NOT EXISTS app.login_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT,
    user_id     BIGINT,
    username    TEXT,
    event       TEXT NOT NULL,                -- 'login_ok' | 'login_fail' | 'logout' | 'bootstrap'
    ok          BOOLEAN NOT NULL DEFAULT TRUE,
    ip          TEXT,
    user_agent  TEXT,
    detail      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_login_events_time ON app.login_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_events_tenant ON app.login_events(tenant_id, created_at DESC);
-- "most recent auth event for this user" — powers the signed-in flag in list_users
CREATE INDEX IF NOT EXISTS idx_login_events_user ON app.login_events(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.conversations (
    conv_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    user_id     BIGINT,
    session_id  TEXT UNIQUE NOT NULL,
    title       TEXT,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    turn_count  INTEGER NOT NULL DEFAULT 0,
    pinned      BOOLEAN NOT NULL DEFAULT FALSE,
    pinned_at   TIMESTAMPTZ,
    archived    BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMPTZ
);
-- Existing deployments: CREATE TABLE IF NOT EXISTS is a no-op once the table
-- is there, so the pin/archive columns are added separately. Idempotent.
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS pinned      BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS pinned_at   TIMESTAMPTZ;
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS archived    BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
-- Conversation context layer (app/context_manager.py): the L2 durable copy of
-- the structured multi-turn state + rolling summary the in-process
-- session_store keeps as L1. Idempotent, additive — no existing row is touched
-- beyond getting NULL defaults for these three columns.
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS summary             TEXT;
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS context_state       JSONB;
ALTER TABLE app.conversations ADD COLUMN IF NOT EXISTS summary_updated_at  TIMESTAMPTZ;
-- The sidebar reads "my unarchived threads, pinned first, newest first".
CREATE INDEX IF NOT EXISTS idx_conv_user_shelf
    ON app.conversations(user_id, archived, pinned DESC, last_at DESC);
CREATE INDEX IF NOT EXISTS idx_conv_tenant_user ON app.conversations(tenant_id, user_id, last_at DESC);

CREATE TABLE IF NOT EXISTS app.conversation_turns (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conv_id             BIGINT NOT NULL REFERENCES app.conversations(conv_id),
    tenant_id           BIGINT NOT NULL,
    user_id             BIGINT,
    session_id          TEXT NOT NULL,
    question            TEXT NOT NULL,
    rewritten_question  TEXT,
    answer              TEXT,
    route               TEXT,
    intent              TEXT,
    schemes             TEXT[],
    resolved_entities   JSONB,
    sql                 TEXT,
    row_count           INTEGER,
    allowed             BOOLEAN,
    denied_by           TEXT,
    latency_ms          NUMERIC,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_turns_conv ON app.conversation_turns(conv_id, created_at);
CREATE INDEX IF NOT EXISTS idx_turns_tenant_time ON app.conversation_turns(tenant_id, created_at DESC);
-- The full answer payload (answer text + result rows + sql + follow-ups), so a
-- reopened chat can redraw its charts. Added separately — CREATE TABLE IF NOT
-- EXISTS is a no-op on existing deployments. Idempotent.
ALTER TABLE app.conversation_turns ADD COLUMN IF NOT EXISTS response JSONB;

CREATE TABLE IF NOT EXISTS app.query_audit (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT,
    user_id      BIGINT,
    username     TEXT,
    session_id   TEXT,
    question     TEXT,
    rewritten_question TEXT,
    route        TEXT,
    granularity  TEXT,
    schemes      TEXT[],
    allowed      BOOLEAN,
    denied_by    TEXT,
    row_count    INTEGER,
    latency_ms   NUMERIC,
    ip           TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON app.query_audit(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user_time ON app.query_audit(user_id, created_at DESC);
"""


async def ensure_schema() -> None:
    await db.execute_script(_DDL)
    logger.info("app schema ready")
    await _seed_default_tenant()
    await _seed_users_from_yaml()


async def _seed_default_tenant() -> int:
    row = await db.fetchrow("SELECT tenant_id FROM app.tenants WHERE code = $1",
                            [settings.DEFAULT_TENANT_CODE])
    if row:
        return row["tenant_id"]
    tid = await db.fetchval(
        "INSERT INTO app.tenants(code, name) VALUES ($1, $2) RETURNING tenant_id",
        [settings.DEFAULT_TENANT_CODE, settings.DEFAULT_TENANT_NAME],
    )
    logger.info("seeded default tenant %s (id=%s)", settings.DEFAULT_TENANT_CODE, tid)
    return tid


async def _seed_users_from_yaml() -> None:
    n = await db.fetchval("SELECT count(*) FROM app.users")
    if n and int(n) > 0:
        return
    path = _ROOT / settings.USERS_FILE
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        logger.warning("appdb: no %s to seed users from", path)
        return
    tid = await _seed_default_tenant()
    seeded = 0
    for rec in data.get("users", []):
        uid = str(rec.get("user_id", "")).strip()
        if not uid:
            continue
        # YAML seed users get username == user_id and a known dev password so the
        # first login works; the admin should rotate these immediately.
        username = rec.get("username", uid)
        pw = rec.get("password", "CHANGE_ME")
        role = rec.get("role", "analyst")
        try:
            await db.execute(
                """INSERT INTO app.users
                   (tenant_id, username, password_hash, name, role, districts, blocks,
                    schemes, granularity_cap, created_by)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'seed')
                   ON CONFLICT (username) DO NOTHING""",
                [tid, username, security.hash_password(pw), rec.get("name"), role,
                 _up(rec.get("districts")), _up(rec.get("blocks")),
                 list(rec.get("schemes") or []), rec.get("granularity_cap")],
            )
            seeded += 1
        except Exception as e:  # noqa: BLE001
            logger.warning("appdb: could not seed user %s: %s", username, e)
    logger.info("appdb: seeded %d users from %s (default password 'CHANGE_ME')", seeded, path.name)


def _up(values) -> list[str]:
    return [str(v).strip().upper() for v in (values or []) if str(v).strip()]


# ── tenants ──────────────────────────────────────────────────────────────
async def list_tenants() -> list[dict]:
    return await db.fetch_rows("SELECT * FROM app.tenants ORDER BY tenant_id")


async def create_tenant(code: str, name: str) -> dict:
    tid = await db.fetchval(
        "INSERT INTO app.tenants(code, name) VALUES ($1,$2) RETURNING tenant_id",
        [code.strip().upper(), name.strip()],
    )
    return await db.fetchrow("SELECT * FROM app.tenants WHERE tenant_id = $1", [tid])


async def get_tenant(tenant_id: int) -> dict | None:
    return await db.fetchrow("SELECT * FROM app.tenants WHERE tenant_id = $1", [tenant_id])


# ── users ────────────────────────────────────────────────────────────────
_USER_COLS = ("user_id, tenant_id, username, name, role, districts, blocks, schemes, "
              "granularity_cap, is_active, created_by, created_at, last_login_at")


async def get_user_by_username(username: str) -> dict | None:
    return await db.fetchrow(
        f"SELECT {_USER_COLS}, password_hash FROM app.users WHERE username = $1", [username])


async def get_user(user_id: int) -> dict | None:
    return await db.fetchrow(f"SELECT {_USER_COLS} FROM app.users WHERE user_id = $1", [user_id])


# u.-qualified column list for the join in list_users()
_USER_COLS_Q = ", ".join(f"u.{c.strip()}" for c in _USER_COLS.split(","))

# is_logged_in: TRUE when the user's most recent auth event is a login rather
# than a logout. Stateless JWT has no session table, so "logged in" is defined
# purely by /api/auth/login vs /api/auth/logout, exactly as the officer
# experiences it. A user who closes the tab without signing out stays TRUE until
# they sign out (or, in practice, log in again from the next session).
_LOGGED_IN_JOIN = """
LEFT JOIN LATERAL (
    SELECT le.event
    FROM app.login_events le
    WHERE le.user_id = u.user_id
      AND le.event IN ('login_ok', 'logout')
    ORDER BY le.created_at DESC
    LIMIT 1
) ev ON TRUE
"""


async def list_users(tenant_id: int | None = None) -> list[dict]:
    sql = (f"SELECT {_USER_COLS_Q}, "
           f"COALESCE(ev.event = 'login_ok', FALSE) AS is_logged_in "
           f"FROM app.users u {_LOGGED_IN_JOIN}")
    if tenant_id is None:
        return await db.fetch_rows(sql + " ORDER BY u.user_id")
    return await db.fetch_rows(sql + " WHERE u.tenant_id = $1 ORDER BY u.user_id", [tenant_id])


async def create_user(*, tenant_id: int, username: str, password: str, name: str | None,
                      role: str, districts=None, blocks=None, schemes=None,
                      granularity_cap: str | None = None, created_by: str = "admin") -> dict:
    uid = await db.fetchval(
        """INSERT INTO app.users
           (tenant_id, username, password_hash, name, role, districts, blocks, schemes,
            granularity_cap, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING user_id""",
        [tenant_id, username.strip(), security.hash_password(password), name, role,
         _up(districts), _up(blocks), list(schemes or []), granularity_cap, created_by],
    )
    return await get_user(uid)


async def update_user(user_id: int, **fields) -> dict | None:
    allowed = {"name", "role", "districts", "blocks", "schemes", "granularity_cap", "is_active"}
    sets, params = [], []
    for k, v in fields.items():
        if k not in allowed or v is None:
            continue
        params.append(_up(v) if k in ("districts", "blocks") else v)
        sets.append(f"{k} = ${len(params)}")
    if fields.get("password"):
        params.append(security.hash_password(fields["password"]))
        sets.append(f"password_hash = ${len(params)}")
    if not sets:
        return await get_user(user_id)
    params.append(user_id)
    await db.execute(f"UPDATE app.users SET {', '.join(sets)} WHERE user_id = ${len(params)}", params)
    return await get_user(user_id)


async def delete_user(user_id: int) -> bool:
    res = await db.execute("UPDATE app.users SET is_active = FALSE WHERE user_id = $1", [user_id])
    return res.endswith("1")


async def purge_user(user_id: int) -> bool:
    """Hard delete — removes the row outright. login_events / conversations /
    query_audit reference user_id without a FK and keep a denormalised username,
    so past history stays readable after the account is gone."""
    res = await db.execute("DELETE FROM app.users WHERE user_id = $1", [user_id])
    return res.endswith("1")


async def touch_login(user_id: int) -> None:
    await db.execute("UPDATE app.users SET last_login_at = NOW() WHERE user_id = $1", [user_id])


# ── login events ─────────────────────────────────────────────────────────
async def log_login(*, event: str, ok: bool, username: str | None = None,
                    user_id: int | None = None, tenant_id: int | None = None,
                    ip: str | None = None, user_agent: str | None = None,
                    detail: str | None = None) -> None:
    try:
        await db.execute(
            """INSERT INTO app.login_events
               (tenant_id, user_id, username, event, ok, ip, user_agent, detail)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8)""",
            [tenant_id, user_id, username, event, ok, ip, (user_agent or "")[:400], detail],
        )
    except Exception as e:  # noqa: BLE001 — auth logging must never break login
        logger.warning("appdb.log_login failed: %s", e)


async def list_login_events(tenant_id: int | None = None, limit: int = 200) -> list[dict]:
    limit = max(1, min(limit, 2000))
    if tenant_id is None:
        return await db.fetch_rows(
            "SELECT * FROM app.login_events ORDER BY created_at DESC LIMIT $1", [limit])
    return await db.fetch_rows(
        "SELECT * FROM app.login_events WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2",
        [tenant_id, limit])
